### ISSUE TITLE
Apply for permission:rewrite the project using C# 

### ISSUE THREAD

**Issue by chenzuo** [lisupeng/tsailun#1]
we want to rewrite 'tsailun' using c# language on ' .Net Core' platform,I hope we can get your help in the future。But the milestone  still follows you .

**Comment by lisupeng** [comment]
That's great you're interested in Tsailun project!
We'll focus on our C++ implementation, we're still working on the development of some important features.
So the Tsailun backend doesn't accept C# PR now.

BTW, besides C++ we also want to provide python version backend. You can contribute C++ or python backend code.
