### ISSUE TITLE
linux lunch fault

### ISSUE THREAD

**Issue by elcky** [lisupeng/tsailun#3]
the path I have added, but still failed

[lighthouse@mail bin]$ TslServer
-bash: TslServer: command not found
[lighthouse@mail bin]$ ./TslServer
-bash: ./TslServer: Permission denied
[lighthouse@mail bin]$ sudo ./TslServer
sudo: ./TslServer: command not found
[lighthouse@mail bin]$

**Comment by lisupeng** [comment]
Please chmod a+x TslServer
BTW, please also add bin dir to LD_LIBRARY_PATH, otherwise you may get error indicates so files missing.
If you want your server running after your console closed, you need run a program background, e.g:
$> nohup ./TslServer &

**Comment by elcky** [comment]
![image](https://user-images.githubusercontent.com/42209617/178284264-ce20c280-e1f0-4145-aec0-23df73a680f4.png)

still cannot run this.

**Comment by lisupeng** [comment]
Can you try launch tsailun with fullpath '/www/wwwroot/tsailun/....../TslServer' ?
If still doesn't work, check if the executable file exists by 'ls /www/wwwroot/tsailun/....../TslServer'

**Comment by lisupeng** [comment]
'ls -l /www/wwwroot/tsailun/....../TslServer' to check if has X permission.
'echo $LD_LIBRARY_PATH'  to check if bin added to the env var.
