### ISSUE TITLE
server lunch success, but can not open the website

### ISSUE THREAD

**Issue by elcky** [lisupeng/tsailun#5]
![image](https://user-images.githubusercontent.com/42209617/179007865-57fbdc7d-ff4a-4da4-b634-0090d6053513.png)

![image](https://user-images.githubusercontent.com/42209617/179008029-1dcd7ca0-ab96-4a55-baf6-234b45ee9638.png)

**Comment by lisupeng** [comment]
Please share reproduce steps.
BTW, please make sure TslServer has read/write permission on <tsailun_root>/server directory.

**Comment by lisupeng** [comment]
Likely due to directory permission.
Please reopen this issue if still doesn't work.

**Comment by elcky** [comment]
![image](https://user-images.githubusercontent.com/42209617/179196619-3680b6d5-1704-47b2-ad98-8b3977e8ffe2.png)

![image](https://user-images.githubusercontent.com/42209617/179196806-187036aa-6c23-4bf6-ad9e-7a58d962e5bd.png)

![image](https://user-images.githubusercontent.com/42209617/179196937-d7ca18e6-9847-4d1c-89d7-e9ea35a21f5a.png)

still can not open

**Comment by lisupeng** [comment]
Can you check your firewall settings if port 6875 enabled both on server and client ?

**Comment by elcky** [comment]
![image](https://user-images.githubusercontent.com/42209617/179206955-8edea535-b12d-4167-bb7c-d24163e41f3e.png)
it is enable

**Comment by lisupeng** [comment]
1. Can you try port 80?
2. Are you using Chrome? Refresh your browser several times, can you see log 'Request from IP xxx' several times ? This is to check if server hang.
